CREATE TABLE ROOM(
  --ROOM_ID BIGSERIAL PRIMARY KEY,
  --NAME VARCHAR(16) NOT NULL,
  --ROOM_NUMBER CHAR(2) NOT NULL UNIQUE,
  --BED_INFO CHAR(2) NOT NULL
  ROOM_ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(40),
  BED_INFO CHAR(3),
  -- ENUM {1K, 2Q, 2D}
  NIGHTS INTEGER(10),
  COST DECIMAL(10),
  DATE_OF_STAY VARCHAR(4),
  HYPERLINK VARCHAR(400)
  --PHOTO VARCHAR(64)
);

CREATE TABLE HOTEL(
  NAME VARCHAR(16),
  -- ROOMS
  CONTACT_NUM VARCHAR(10)
  
  --EMPLOYEE_ID CHAR(36) PRIMARY KEY,
  --FIRST_NAME VARCHAR(64),
  --LAST_NAME VARCHAR(64),
  --POSITION VARCHAR(64)
);