--INSERT INTO ROOM (NAME VARCHAR(40), BED_INFO CHAR(2), NIGHTS INTEGER(10), COST DECIMAL(19,4)) values ('Baymont Mackinaw City','159.00', 2, 159.00);
INSERT INTO station (name, street) values ('Sunoco Gas Station', '527 S Grand Traverse St');
INSERT INTO station (name, street) values ('Sunoco Gas Station', '1670 Dupont St');
INSERT INTO station (name, street) values ('Marathon Gas Station','2800 Corunna Rd');
INSERT INTO station (name, street) values ('Speedway Gas Station', '3155 Miller Rd');
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();
-- INSERT INTO room (name, street) values ();