--INSERT INTO ROOM (NAME VARCHAR(16), BED_INFO CHAR(2), NIGHTS INTEGER(10), COST DECIMAL(19,4)) values ('Baymont Mackinaw City','159.00', 2, 159.00);
INSERT INTO room (name, bed_info, nights, stay_start) values ('La Quinta Ronks',               '2Q' , 2, '0328');
INSERT INTO room (name, bed_info, nights, stay_start) values ('La Quinta Ronks',               '1K' , 2, '0328');
INSERT INTO room (name, bed_info, nights, stay_start) values ('La Quinta Ronks',               '2Q' , 2, '0404');
INSERT INTO room (name, bed_info, nights, stay_start) values ('La Quinta Ronks',               '1K' , 2, '0404');
INSERT INTO room (name, bed_info, nights, stay_start) values ('La Quinta Ronks',               '2Q' , 2, '0411');
INSERT INTO room (name, bed_info, nights, stay_start) values ('La Quinta Ronks',               '1K' , 2, '0411');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Wyndham Lancaster',             '2Q' , 2, '0328');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Wyndham Lancaster',             '1K' , 2, '0328');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Wyndham Lancaster',             '2Q' , 2, '0411');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Wyndham Lancaster',             '1K' , 2, '0411');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Clarion Inn Strasburg',         '2Q' , 2, '0328');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Clarion Inn Strasburg',         '1K' , 2, '0328');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Clarion Inn Strasburg',         '2QS', 2, '0328');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Clarion Inn Strasburg',         '2Q' , 2, '0411');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Clarion Inn Strasburg',         '1KS', 2, '0411');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Holiday Inn Express Lilitz',    '2Q' , 2, '0328');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Holiday Inn Express Lilitz',    '2Q' , 2, '0411');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Holiday Inn Express Lilitz',    '2QS', 2, '0411');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Holiday Inn Express Lilitz',    '1K' , 2, '0411');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Holiday Inn Express Strasburg', '2Q' , 2, '0404');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Holiday Inn Express Strasburg', '2QS', 2, '0404');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Holiday Inn Express Strasburg', '1KS', 2, '0404');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Holiday Inn Express Strasburg', '2Q' , 2, '0411');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Holiday Inn Express Strasburg', '2QS' ,2, '0411');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Holiday Inn Express Strasburg', '1KS' ,2, '0411');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Fairfield Inn Branson',         '2Q' , 2, '0404');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Fairfield Inn Branson',         '1K' , 2, '0404');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Fairfield Inn Branson',         '2Q' , 2, '0411');
INSERT INTO room (name, bed_info, nights, stay_start) values ('Fairfield Inn Branson',         '1K' , 2, '0411');